<a href="https://colab.research.google.com/github/SAMPATHKUMAR12/DL_Lab/blob/main/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
x= tf.constant(4, shape=(3,3))
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]], dtype=int32)>

In [ ]:
tf.constant([[2,4,6],[4,7,8]])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 4, 6],
       [4, 7, 8]], dtype=int32)>